### ISSUE TITLE
ROS kinetic: ImportError: No module named terminal_color

### ISSUE THREAD

**Issue by gsilano** [gsilano/CrazyS#5]
After updating ROS packages via apt commands, I am getting the following error when running catkin_make

 ```
$ catkin_make
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 13, in <module>
    from catkin.terminal_color import disable_ANSI_colors, fmt
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/terminal_color.py", line 2, in <module>
    from catkin_pkg.terminal_color import *  # noqa
ImportError: No module named terminal_color
 ```

 ```
$ apt show ros-kinetic-catkin
Package: ros-kinetic-catkin
Version: 0.7.14-0xenial-20180809-132632-0800
Priority: extra
Section: misc
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 608 kB
Depends: cmake, google-mock, libgtest-dev, python-catkin-pkg (>> 0.4.3), python-empy, python-nose
Homepage: http://www.ros.org/wiki/catkin
Download-Size: 112 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
Description: Low-level build system macros and infrastructure for ROS.
 ```

I have no other version of catkin on my system. I am running Ubuntu 16.04

**Comment by gsilano** [comment]
Please check the existing questions about the same topic:

- https://answers.ros.org/question/294780/ubuntu18-and-ros-melodic-catkin-error-importerror-no-module-named-terminal_color/

- https://answers.ros.org/question/301702/ros-kinetic-importerror-no-module-named-terminal_color/
